version: "3.8"

services:
  app:
    build: .                
    ports:
      - "8000:8000"         
    env_file:
      - .env                # Load environment variables from .env
    volumes:
      - .:/app              # Mount local project dir into container's /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
